version: "3.3"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_DB: account
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_PORT: 5432
        ports:
            - 5432:5432
    migrate:
        image: migrate/migrate
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations/", "-database",  "postgres://test:test@db:5432/account?sslmode=disable", "up"]
        links: 
            - db

